fos_elastica:
  clients:
    default: { host: localhost, port: 8000 } # Port personnalisé
  indexes:
    app:
      properties:
        nom: ~
      persistence:
        driver: orm
        model: App\Entity\Event